### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by nahupyrope** [BinkanSalaryman/Discord-Audio-Stream-Bot#60] opened 2021-11-13 20:47 UTC
17:47:12 [main] INFO  net.runee.gui.MainFrame - Hello World!
17:47:12 [main] ERROR net.runee.gui.MainFrame - Uncaught exception in thread main
jouvieje.bass.exceptions.BassException: no bass in java.library.path or org.lwjgl.librarypath
	at jouvieje.bass.BassInit.loadLibraries(BassInit.java:96) ~[Discord%20Audio%20Stream%20Bot.jar:na]
	at net.runee.gui.MainFrame.main(MainFrame.java:52) ~[Discord%20Audio%20Stream%20Bot.jar:na]
17:47:14 [DASB Shutdown Hook] INFO  net.runee.gui.MainFrame - Goodbye!

It's a new windows install, have installed Java on it's latest version.

**Comment by BinkanSalaryman** [comment] 2021-11-14 22:56
1. Try both **run win64.bat** and **run win32.bat**, one of them should work
2. If it didn't help, try running the bot program using java 11

**Comment by BinkanSalaryman** [comment] 2021-12-26 14:19
I'm closing this as a duplicate of #61

**Closed by BinkanSalaryman** 2021-12-26 14:19 UTC
